[package]
name = "iota-crypto"
version = "0.4.2"
license = "Apache-2.0"
authors = [
  "Gustav Behm <gustav.behm@iota.org>",
  "Daniel Thompson-Yvetot <daniel.yvetot@iota.org>"
]
edition = "2018"
readme = "README.md"
keywords = [ "iota", "cryptography", "security" ]
categories = [ "security" ]
description = "The canonical source of cryptographic ground-truth for all IOTA Rust projects"
homepage = "https://iota.org"
repository = "https://github.com/iotaledger/crypto.rs"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [ "--cfg", "docsrs" ]

[lib]
name = "crypto"

[features]
default = [ ]
std = [ ]
aes-kw = [ "aes-crate" ]
chacha = [ "chacha20poly1305", "cipher" ]
ed25519 = [ "ed25519-zebra" ]
x25519 = [ "x25519-dalek" ]
random = [ "getrandom" ]
aes = [ "aes-gcm", "cipher" ]
blake2b = [ "blake2", "digest" ]
curl-p = [ "bee-ternary" ]
sha = [ "sha2", "digest" ]
hmac = [ "hmac_" ]
pbkdf = [ "pbkdf2" ]
bip39 = [ "pbkdf", "hmac", "sha", "pbkdf", "unicode-normalization" ]
bip39-en = [ "bip39" ]
bip39-jp = [ "bip39" ]
slip10 = [ "hmac", "sha", "ed25519", "random", "serde" ]
cipher = [ "aead", "generic-array" ]

[dependencies]
chacha20poly1305 = { version = "0.8.0", optional = true }

  [dependencies.ed25519-zebra]
  version = "2.2.0"
  optional = true
  default-features = false

  [dependencies.x25519-dalek]
  version = "1.1.0"
  optional = true
  default-features = false
  features = [ "u64_backend" ]

  [dependencies.getrandom]
  version = "0.2.0"
  optional = true
  default-features = false

  [dependencies.aead]
  version = "0.3"
  optional = true
  default-features = false

  [dependencies.generic-array]
  version = "0.14"
  optional = true
  default-features = false

  [dependencies.aes-crate]
  version = "0.6"
  package = "aes"
  optional = true
  default-features = false

  [dependencies.aes-gcm]
  version = "0.8.0"
  optional = true
  features = [ "aes" ]
  default-features = false

  [dependencies.blake2]
  version = "0.9.1"
  optional = true
  default-features = false

  [dependencies.bee-ternary]
  version = "0.3.4-alpha"
  optional = true
  default-features = false

  [dependencies.sha2]
  version = "0.9.3"
  optional = true
  default-features = false

  [dependencies.hmac_]
  version = "0.10.1"
  package = "hmac"
  optional = true
  default-features = false

  [dependencies.pbkdf2]
  version = "0.7.3"
  optional = true
  default-features = false

  [dependencies.unicode-normalization]
  version = "0.1.17"
  optional = true
  default-features = false

  [dependencies.digest]
  version = "0.9.0"
  optional = true
  default-features = false

  [dependencies.serde]
  version = "1.0.123"
  optional = true
  features = [ "derive" ]

[dev-dependencies]
hex = "0.4.2"
rand = "0.8.3"
serde = { version = "1.0.117", features = [ "derive" ] }
serde_json = "1.0.64"
